fn main() {
    let manifest_dir =
        std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    println!("cargo:rustc-link-arg-bins=--nmagic");
    println!("cargo:rustc-link-arg-bins=-Tlink.x");
    println!("cargo:rerun-if-changed=model/cmsis/imu_model.c");
    println!("cargo:rerun-if-changed=model/cmsis/imu_model.h");
    println!("cargo:rerun-if-changed=model/cmsis/imu_model_weights.h");

    let cmsis_nn = manifest_dir.join("third_party/CMSIS-NN");
    let cmsis_core = manifest_dir.join("third_party/CMSIS_6/CMSIS/Core/Include");
    if !cmsis_nn.exists() || !cmsis_core.exists() {
        panic!(
            "CMSIS sources are missing. Expected third_party/CMSIS-NN and third_party/CMSIS_6. \
             Run: git clone --depth 1 https://github.com/ARM-software/CMSIS-NN.git third_party/CMSIS-NN && \
             git clone --depth 1 https://github.com/ARM-software/CMSIS_6.git third_party/CMSIS_6"
        );
    }

    let mut sources = vec![
        manifest_dir.join("model/cmsis/imu_model.c"),
        manifest_dir.join("model/cmsis/cmsis_compat.c"),
    ];

    for dir in [
        "third_party/CMSIS-NN/Source/ActivationFunctions",
        "third_party/CMSIS-NN/Source/BasicMathFunctions",
        "third_party/CMSIS-NN/Source/ConvolutionFunctions",
        "third_party/CMSIS-NN/Source/FullyConnectedFunctions",
        "third_party/CMSIS-NN/Source/NNSupportFunctions",
        "third_party/CMSIS-NN/Source/PoolingFunctions",
    ] {
        let dir_path = manifest_dir.join(dir);
        for entry in std::fs::read_dir(&dir_path).expect("read CMSIS-NN source directory") {
            let path = entry.expect("read CMSIS-NN source entry").path();
            if path.extension().and_then(|ext| ext.to_str()) == Some("c") {
                println!("cargo:rerun-if-changed={}", path.display());
                sources.push(path);
            }
        }
    }

    let out_dir = std::path::PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    generate_rust_model_constants(&manifest_dir, &out_dir);
    let c_compiler = cmsis_c_compiler();

    for (idx, source) in sources.iter().enumerate() {
        let stem = source
            .file_stem()
            .and_then(|name| name.to_str())
            .unwrap_or("cmsis");
        let object = out_dir.join(format!("{idx:03}_{stem}.o"));
        let mut command = std::process::Command::new(&c_compiler.program);
        command.args(&c_compiler.flags);
        let status = command
            .arg("-mthumb")
            .arg("-mcpu=cortex-m33")
            .arg("-ffreestanding")
            .arg("-fno-builtin")
            .arg("-O3")
            .arg("-Wno-unknown-attributes")
            .arg("-Wno-unknown-pragmas")
            .arg("-DARM_MATH_DSP")
            .arg("-DCMSIS_NN_USE_SINGLE_ROUNDING")
            .arg(format!("-I{}", manifest_dir.join("model/cmsis").display()))
            .arg(format!("-I{}", cmsis_nn.join("Include").display()))
            .arg(format!("-I{}", cmsis_core.display()))
            .arg("-c")
            .arg(source)
            .arg("-o")
            .arg(&object)
            .status()
            .unwrap_or_else(|err| panic!("run {} for CMSIS-NN source: {err}", c_compiler.program));
        if !status.success() {
            panic!(
                "{} failed while compiling {}",
                c_compiler.program,
                source.display()
            );
        }
        println!("cargo:rustc-link-arg-bins={}", object.display());
    }
}

struct CCompiler {
    program: String,
    flags: Vec<&'static str>,
}

fn cmsis_c_compiler() -> CCompiler {
    let program = std::env::var("CMSIS_CC").unwrap_or_else(|_| "clang".to_string());
    println!("cargo:rerun-if-env-changed=CMSIS_CC");
    if program.contains("clang") {
        CCompiler {
            program,
            flags: vec!["--target=thumbv8m.main-none-eabihf"],
        }
    } else {
        CCompiler {
            program,
            flags: Vec::new(),
        }
    }
}

fn generate_rust_model_constants(manifest_dir: &std::path::Path, out_dir: &std::path::Path) {
    let header_path = manifest_dir.join("model/cmsis/imu_model.h");
    let header = std::fs::read_to_string(header_path).expect("read imu_model.h");
    let input_len = read_define_usize(&header, "IMU_MODEL_INPUT_LEN");
    let channels = read_define_usize(&header, "IMU_MODEL_CHANNELS");
    let classes = read_define_usize(&header, "IMU_MODEL_CLASSES");
    let input_size = input_len * channels;
    let generated = format!(
        "\
// Generated by build.rs from model/cmsis/imu_model.h.
pub const INPUT_LEN: usize = {input_len};
pub const CHANNELS: usize = {channels};
pub const INPUT_SIZE: usize = {input_size};
pub const CLASSES: usize = {classes};
"
    );
    std::fs::write(out_dir.join("model_constants.rs"), generated)
        .expect("write generated Rust model constants");
}

fn read_define_usize(header: &str, name: &str) -> usize {
    for line in header.lines() {
        let mut parts = line.split_whitespace();
        if parts.next() == Some("#define") && parts.next() == Some(name) {
            let value = parts
                .next()
                .unwrap_or_else(|| panic!("missing value for {name}"));
            return value
                .parse::<usize>()
                .unwrap_or_else(|_| panic!("expected integer value for {name}, got {value}"));
        }
    }
    panic!("missing #define {name} in model/cmsis/imu_model.h");
}
